### PR TITLE
Rename Generic System to Custom Generation Profile

### PR DESCRIPTION
**Pull request by mjprilliman**
-See https://github.com/NREL/SAM/pull/1890
-Fixes https://github.com/NREL/SAM/issues/1849
-Update generic cmod, rename for custom generation
-Include reference to Generic System name in cmod description for backwards reference
-Update test naming conventions, test files
-replace key word reference to generic system where appropriate
-Leave 'Generic CSP' references as they are

### CODE REVIEW

**Review by cpaulgilman — CHANGES_REQUESTED** [review]
Generally looks good -- a few requests:

* Change UI form group label from "Generic System" to "Custom Generation" on Custom Generation Plant and Custom Generation Costs forms. Also note "Generic Battery" in group label for Custom Generation Battery Costs form -- should that be "Custom Generation Battery"?

image

* Remove "formerly" from configuration tree to make it cleaner and take up less space.

* Rename "Power Plant Losses" on Custom Generation Profile page to "Losses".

* Rename group label on Power Plant page from "Custom Generation Profile Power Plant" to "Custom Generation Profile".

* Rename "Power Plant" in navigation menu to "Generation Profile" for hybrid, generic, and generic-battery configurations.

**Comment by cpaulgilman** [comment]
Testing a build on macOS 15.1 Sequoia on Apple M1results in following error:

```
Undefined symbols for architecture arm64:
  "_cm_entry_custom_generation", referenced from:
      module_table in sscapi.o
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Review by cpaulgilman — APPROVED** [review]
