### ISSUE TITLE
VS 2017 upgrade compiler issue

### ISSUE THREAD

**Issue by mjwagner2** [NREL/ssc#141]
After upgrading Visual Studio 2017 (v15) to 15.6.1, the solarpilot module fails to compile, with the error message:
```
error C2664: cannot convert from 'std::pair<const _Kty,_Ty>' to 'const std::pair<const _Kty,_Ty>'
```
The issue is related to the ```struct _inst``` contained in the ```class AutoOptHelper``` in AutoPilot_API.cpp, and the hash ```unordered_map<std::string, _inst> items``` member.
